version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      - TZ=America/Los_Angeles
      - WEBPASSWORD=${PIHOLE_PASSWORD:-CHANGE_ME_TO_YOUR_PASSWORD}
      - FTLCONF_LOCAL_IPV4=192.168.50.215
      - PIHOLE_DNS_1=9.9.9.9#53
      - PIHOLE_DNS_2=149.112.112.112#53
      - DNSSEC=true
      - DNSMASQ_LISTENING=all
    volumes:
      - ./:/etc/pihole/
      - ./dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 9.9.9.9
    healthcheck:
      test: ["CMD", "dig", "+norecurse", "+retry=0", "@127.0.0.1", "pi.hole"]
      interval: 30s
      timeout: 10s
      retries: 5
