version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      - TZ=America/Los_Angeles
      - WEBPASSWORD=${PIHOLE_PASSWORD:-CHANGE_ME_TO_YOUR_PASSWORD}
      - FTLCONF_LOCAL_IPV4=192.168.50.215
      - PIHOLE_DNS_1=9.9.9.9#53
      - PIHOLE_DNS_2=149.112.112.112#53
      - DNSSEC=true
      - DNSMASQ_LISTENING=all
    volumes:
      - ./:/etc/pihole/
      - ./dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 9.9.9.9
    healthcheck:
      test: ["CMD", "dig", "+norecurse", "+retry=0", "@127.0.0.1", "pi.hole"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - pihole_network

  # Cloudflared for DNS-over-HTTPS
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: proxy-dns --address 0.0.0.0 --port 5054 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query
    ports:
      - "5054:5054/udp"
    restart: unless-stopped
    networks:
      - pihole_network

  # Pi-hole Exporter for Prometheus metrics
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:latest
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD=${PIHOLE_PASSWORD:-CHANGE_ME_TO_YOUR_PASSWORD}
      - INTERVAL=30s
      - PORT=9617
    ports:
      - "9617:9617"
    restart: unless-stopped
    depends_on:
      - pihole
    networks:
      - pihole_network

  # Unbound for recursive DNS (optional - more privacy)
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    volumes:
      - ./unbound:/opt/unbound/etc/unbound/
    restart: unless-stopped
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge
